services:
  kuma2awtrix:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/altepizza/kuma2awtrix:latest
    restart: unless-stopped
    environment:
      - KUMA2AWTRIX_BROKERPORT=${MQTT_BROKER_HOST_PORT}
      - KUMA2AWTRIX_BROKERHOST=${MQTT_BROKER_HOST_URL}
      - KUMA2AWTRIX_USERNAME=${MQTT_USERNAME}
      - KUMA2AWTRIX_PASSWORD=${MQTT_PASSWORD}
      - KUMA2AWTRIX_AWTRIX_PREFIX=${AWTRIX_PREFIX}
    ports:
      - "8181:8181"
